version: '3.9'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"  # jaeger UI
      - "14268"
      - "14250"

  zipkin:
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  # OpenTelemetry Collector
  otelcol:
    image: otel/opentelemetry-collector:latest
    #restart: always
    command: [ "--config=/etc/otelcol-config.yml" ]
    volumes:
      - ./otelcollector/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317"        # OTLP gRPC receiver
      - "4318"        # OTLP over HTTP receiver      
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension      
      - "55679:55679" # zpages extension
    depends_on:
       - jaeger
       - zipkin

  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  webapp:
    build:
      context: .
      dockerfile: ./src/WebApp/Dockerfile
    image: webapp
    ports:
      - 8080:8080
    environment:
      UseTracingExporter: otlp
      UseLogExporter: otlp
      UseMetricsExporter: otlp
      ServiceName: "webapp"
      Zipkin__Endpoint: http://zipkin:9411/api/v2/spans
      Otlp__Endpoint: http://otelcol:4317
      Kestrel__Endpoints__Http__Url: http://webapp:8080
    depends_on:
      - zipkin
      - otelcol