global:
  scrape_interval: 5s 
  evaluation_interval: 5s 
  # scrape_timeout is set to the global default (10s).
scrape_configs:
  # - job_name: prometheus
  #   static_configs:
  #     - targets: ["prometheus:9090"]
  # - job_name: 'webapp'
  #   static_configs:
  #     - targets: ["webapp:8080"]
  - job_name: 'otelcol'
    scrape_interval: 10s
    static_configs:
      - targets: ['otelcol:8889']
      - targets: ['otelcol:8888']      